server:
  port: 8080
spring:  
  application:
    name: Api Gateway
zuul:
  routes:
    usermanagement-microservice:
      path: /login/**
      url: http://127.0.0.1:8081/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
    ElasticSearch-Microservice:
      path: /elasticSearchApi/**
      url: http://127.0.0.1:8083/
    users-service:
      path: /users/**
      url: http://127.0.0.1:8081/

talan.security.jwt.secret: otherpeopledontknowit
zuul.ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin